services:

  postgres-db:
    image: postgres:16-alpine
    container_name: banking_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
        - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - banking-network

  backend:
    build: .
    container_name: banking_backend
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - banking-network


volumes:
  postgres_data:
    driver: local


networks:
  banking-network:
    driver: bridge
