server:
  port: 8080
spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
app:
  encryption:
    key: ${ENCRYPTION_KEY}
  jwt:
    secret: ${APP_JWT_SECRET}
    expirationMs: ${ACCESS_TOKEN_TIME}
    refreshExpirationMs: ${REFRESH_TOKEN_TIME}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
initial:
   user:
     login: ${LOGIN_INIT_USER}
     pass: ${PASS_INIT_USER}
     email: ${EMAIL_INIT_USER}
     lastname: ${LASTNAME_INIT_USER}
     firstname: ${FIRSTNAME_INIT_USER}
logging:
  level:
    # Включаем DEBUG для всего Spring Security
    org.springframework.security: DEBUG