server:
  port: 8080
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_api_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expirationMs: ${ACCESS_TOCKEN_TIME}
    refreshExpirationMs: ${REFRASH_TOCKEN_TIME}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html